import type { CustomerRow, StatusKey } from "./types";

// 15 条 mock 数据：人名/邮箱/公司/金额/日期保留原文不翻译
// status 用 stable key，展示时 t(`status.${key}`) 翻译
const data: CustomerRow[] = [
  {
    id: "c-001",
    name: "Eleanor Pena",
    email: "eleanor.pena@acme.io",
    company: "Acme Corporation",
    status: "vip",
    spent: 28430,
    createdAt: "2024-03-12",
    avatarColor: "bg-chart-2/20",
  },
  {
    id: "c-002",
    name: "Hiroshi Tanaka",
    email: "h.tanaka@orbital.dev",
    company: "Orbital Labs",
    status: "active",
    spent: 15200,
    createdAt: "2024-05-22",
    avatarColor: "bg-chart-1/20",
  },
  {
    id: "c-003",
    name: "Amara Okafor",
    email: "amara@northwind.co",
    company: "Northwind Traders",
    status: "atRisk",
    spent: 840,
    createdAt: "2025-01-03",
    avatarColor: "bg-destructive/20",
  },
  {
    id: "c-004",
    name: "Liam Chen",
    email: "liam.chen@brightline.app",
    company: "Brightline",
    status: "active",
    spent: 12380,
    createdAt: "2024-07-18",
    avatarColor: "bg-chart-3/20",
  },
  {
    id: "c-005",
    name: "Sofia Rossi",
    email: "sofia@monteverde.studio",
    company: "Monteverde Studio",
    status: "inactive",
    spent: 0,
    createdAt: "2023-11-09",
    avatarColor: "bg-muted",
  },
  {
    id: "c-006",
    name: "Moses Adeyemi",
    email: "moses@paystack.merge",
    company: "Paystack Merge",
    status: "vip",
    spent: 42100,
    createdAt: "2023-08-14",
    avatarColor: "bg-chart-2/20",
  },
  {
    id: "c-007",
    name: "Yuki Saito",
    email: "yuki.saito@kaze.jp",
    company: "Kaze Holdings",
    status: "active",
    spent: 9650,
    createdAt: "2025-02-27",
    avatarColor: "bg-chart-1/20",
  },
  {
    id: "c-008",
    name: "Noah Williams",
    email: "noah.w@summitpeak.io",
    company: "Summit Peak",
    status: "atRisk",
    spent: 1320,
    createdAt: "2024-09-30",
    avatarColor: "bg-destructive/20",
  },
  {
    id: "c-009",
    name: "Priya Nair",
    email: "priya.nair@lumina.in",
    company: "Lumina Systems",
    status: "active",
    spent: 18750,
    createdAt: "2024-04-05",
    avatarColor: "bg-chart-3/20",
  },
  {
    id: "c-010",
    name: "Mateo García",
    email: "mateo@andalus.es",
    company: "Andalus Media",
    status: "vip",
    spent: 35600,
    createdAt: "2023-06-21",
    avatarColor: "bg-chart-2/20",
  },
  {
    id: "c-011",
    name: "Chloé Dubois",
    email: "chloe@parisienne.fr",
    company: "Parisienne Co.",
    status: "inactive",
    spent: 0,
    createdAt: "2023-12-15",
    avatarColor: "bg-muted",
  },
  {
    id: "c-012",
    name: "Daniel Kim",
    email: "d.kim@hanbridge.kr",
    company: "Hanbridge",
    status: "active",
    spent: 7420,
    createdAt: "2025-03-08",
    avatarColor: "bg-chart-1/20",
  },
  {
    id: "c-013",
    name: "Aisha Hassan",
    email: "aisha@deltaforge.ae",
    company: "Deltaforge",
    status: "atRisk",
    spent: 2150,
    createdAt: "2024-10-19",
    avatarColor: "bg-destructive/20",
  },
  {
    id: "c-014",
    name: "Lucas Müller",
    email: "lucas@nordstrom.de",
    company: "Nordstrom GmbH",
    status: "vip",
    spent: 51200,
    createdAt: "2023-09-02",
    avatarColor: "bg-chart-2/20",
  },
  {
    id: "c-015",
    name: "Ingrid Larsen",
    email: "ingrid@nordlys.no",
    company: "Nordlys AS",
    status: "active",
    spent: 4380,
    createdAt: "2025-04-11",
    avatarColor: "bg-chart-3/20",
  },
];

export const customerData: CustomerRow[] = data;

// 用于统计卡的聚合计算
export function countByStatus(rows: CustomerRow[], status: StatusKey): number {
  return rows.filter((r) => r.status === status).length;
}

export function totalSpent(rows: CustomerRow[]): number {
  return rows.reduce((sum, r) => sum + r.spent, 0);
}
